### ISSUE TITLE
Review Hw#1

### ISSUE THREAD

**Issue by mpsingh01** [mpsingh01/HW-1-Dropbox#1]
cc @thecodepath

**Comment by drnick23** [comment]
This weeks goal was to achieve parity with prototyping frameworks by learning how to layout views, create hotspots, and navigate between screens using various animations.

Great job on completing all the required tasks! Your code is particularly well structured and your naming of files is spot on. I get the feeling from your attention and ability in class, that you could be hitting all the optionals. I'm not sure how much time you spent on this week's task (please include the hours spent next time) -- but I'd love to see what you can do for next week's assignment which will offer a much greater challenge.
